#Astatine Online
world_setting:
  motd: 'ASTATINE ONLINE'
  minelist: 'https://minelist.kr/servers/astn.iptime.org'
  discord: 'https://discord.com/invite/May9BkW7yR'
  notion: 'https://jaxple.notion.site/Project-Astatine-e000a5d52aaa4611a63fd62629ea0f36?pvs=4'