name: R01
version: '${version}'
main: teamzesa.R01
api-version: '1.20'
authors: [ JAXPLE ]

commands:
  SaveUserData:
    description: 유저 데이터를 저장합니다.
  Motd:
    description: Motd를 설정합니다.
  몸통:
    description: 손에 든 아이템을 몸통에 착용합니다.
  바지:
    description: 손에 든 아이템을 바지에 착용합니다.
  신발:
    description: 손에 든 아이템을 신발에 착용합니다.
  setHealth:
    description: 체력을 초기화 합니다.
  vo:
    description: DebugValue
  meteor:
    description: 운석을 떨어트립니다.
  god:
    description: 갓 모드를 활성화 합니다.
  dataFileReload:
    description: config를 Reload 합니다.
  moderator:
    description: 관리자 권한부여
  hat:
    description: 손에 든 아이템을 머리에 착용합니다.
  totem:
    description: 토템을 합칩니다.
  fly:
    description: 하늘을 납니다.
  공지:
    description: 공지를 키거나 끕니다.
  강화:
    description: 강화창을 엽니다.