name: R01
version: '${version}'
main: teamzesa.R01
api-version: '1.20'
authors: [ JAXPLE ]

permissions:
  SpeedLimit.bypass:
    description: Bypass the speed limit
    default: op

commands:
  ExportR01Object:
    description: R01프로젝트에 모든 Object가 Export 됩니다.
  Motd:
    description: Motd를 설정합니다.
  setHealth:
    description: 체력을 초기화 합니다.
  vo:
    description: DebugValue
  god:
    description: 무적을 활성화 합니다.
  dataFileReload:
    description: config 을 Reload 합니다.
  moderator:
    description: 관리자 권한부여
  hat:
    description: 손에 든 아이템을 머리에 착용합니다.
  totem:
    description: 토템을 합칩니다.
  fly:
    description: 하늘을 납니다.
  공지:
    description: 공지를 키거나 끕니다.
  강화:
    description: 강화창을 엽니다.
  enhance:
    description: 강화를 설정합니다.